### ISSUE TITLE
parameter_error on order modify

### ISSUE THREAD

**Issue by ethene** [thomasbeukema/cobinhood_api#3]
request:
`
https://api.cobinhood.com:443 "PUT /v1/trading/orders/f3a39c8d-a68f-4990-a2e9-de7c33fbe502?price=0.00000043&size=70 HTTP/1.1
`

response:
`
 {'success': False, 'error': {'error_code': 'parameter_error'}, 'request_id': '99c15ec6e708f953'}
`

**Comment by thomasbeukema** [comment]
Hi Ethene,

I wonder how you got your orderid, since this doesn't seem like a valid one. I suggest you take a look at how a valid one would look in README. I will close this issue since this isn't a bug in the API, but in your application.
